import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from 'next/link';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className="m-5">
        <Link className="m-5 text-2xl" href="/">
          Home
        </Link>
        <Link className="m-5 text-2xl" href="/bring">
          Bring
        </Link>
      </nav>
      {children}
      </body>
    </html>
  );
}
