[package]
name = "weather"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
colored = "2.1.0"
reqwest = { version = "0.12.2", features = ["blocking", "json"]}
serde = { version = "1.0.197", features = ["derive"]}
serde_json = "1.0.115"
