[package]
name = "weather"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
reqwest = "0.12.2"
serde_json = "1.0.115"
tokio = { version = "1.37.0", features = ["full"] }
